service: poorman-rag
frameworkVersion: '>=3.24.1'
useDotenv: true

provider:
  name: aws
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  profile: ${env:AWS_PROFILE}
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET}
  runtime: provided.al2023
  logRetentionInDays: 14
  versionFunctions: false
  
  environment:
    RAG_BUCKET: ${env:RAG_BUCKET}
    RAG_SEARCH_TYPE: ${env:RAG_SEARCH_TYPE, 'hybrid'}
    LOG_LEVEL: INFO
    LD_LIBRARY_PATH: /var/task/lib

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource: "arn:aws:s3:::${env:RAG_BUCKET}"
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "arn:aws:s3:::${env:RAG_BUCKET}/*"

package:
  individually: true

functions:
  mcp-server:
    name: ${self:service}-${sls:stage}-server
    memorySize: 3008
    ephemeralStorageSize: 2048
    package:
      artifact: deployment.zip
    handler: bootstrap
    timeout: 60
    url: true
